In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [2]:
crimes = pd.read_excel('theft.xlsx')

In [3]:
traffic = pd.read_csv('chickens.csv')

In [4]:
crimes.columns

Index(['Region', 'Sub Region', 'Country', 'Count', 'Rate', 'Year'], dtype='object')

In [5]:
traffic.columns

Index(['Unnamed: 0', 'Domain Code', 'Domain', 'Area Code', 'Area',
       'Element Code', 'Element', 'Item Code', 'Item', 'Year Code', 'Year',
       'Unit', 'Value', 'Flag', 'Flag Description', 'Note', 'Value Extended'],
      dtype='object')

In [6]:
traffic.rename(columns={'Area':'Country'}, inplace=True)

In [7]:
traffic.columns

Index(['Unnamed: 0', 'Domain Code', 'Domain', 'Area Code', 'Country',
       'Element Code', 'Element', 'Item Code', 'Item', 'Year Code', 'Year',
       'Unit', 'Value', 'Flag', 'Flag Description', 'Note', 'Value Extended'],
      dtype='object')

In [8]:
criminal_traffic = traffic.merge(crimes, on=['Country', 'Year'])

In [9]:
criminal_traffic.head(3)
criminal_traffic['CCM'] = criminal_traffic['Count']*criminal_traffic['Value Extended']/1000000
criminal_traffic[['Country','Count','Value Extended','CCM']]
recent_filter = criminal_traffic['Year'] > 2013
export_filter = criminal_traffic['Element'] == 'Export Quantity'
recent_traffic = criminal_traffic[recent_filter & export_filter]
recent_traffic.sort_values(by='CCM', ascending=False)

,Unnamed: 0,Domain Code,Domain,Area Code,Country,Element Code,Element,Item Code,Item,Year Code,...,Value,Flag,Flag Description,Note,Value Extended,Region,Sub Region,Count,Rate,CCM
2176,45606,TA,Live animals,231,United States of America,5909,Export Quantity,1057,Chickens,2014,...,90341.0,NaN,Official data,NaN,90341000.0,Americas,Northern America,5809100,1828.377919,5.247999e+08
764,17056,TA,Live animals,79,Germany,5909,Export Quantity,1057,Chickens,2016,...,333700.0,NaN,Official data,NaN,333700000.0,Europe,Western Europe,1290481,1576.172925,4.306335e+08
760,17052,TA,Live animals,79,Germany,5909,Export Quantity,1057,Chickens,2015,...,292094.0,NaN,Official data,NaN,292094000.0,Europe,Western Europe,1348955,1650.950315,3.940217e+08
2184,45614,TA,Live animals,231,United States of America,5909,Export Quantity,1057,Chickens,2016,...,68995.0,NaN,Official data,NaN,68995000.0,Americas,Northern America,5638500,1749.839046,3.890283e+08
2180,45610,TA,Live animals,231,United States of America,5909,Export Quantity,1057,Chickens,2015,...,61736.0,NaN,Official data,NaN,61736000.0,Americas,Northern America,5723500,1788.989776,3.533460e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1042,21910,TA,Live animals,109,Jamaica,5909,Export Quantity,1057,Chickens,2014,...,1.0,NaN,Official data,NaN,1000.0,Americas,Caribbean,447,15.617974,4.470000e-01
1406,29399,TA,Live animals,149,Nepal,5909,Export Quantity,1057,Chickens,2016,...,0.0,NaN,Official data,NaN,0.0,Asia,Southern Asia,1274,4.396578,0.000000e+00
1840,38320,TA,Live animals,200,Singapore,5909,Export Quantity,1057,Chickens,2014,...,0.0,F,FAO estimate,NaN,0.0,Asia,South-Eastern Asia,16182,297.007787,0.000000e+00
1844,38324,TA,Live animals,200,Singapore,5909,Export Quantity,1057,Chickens,2015,...,0.0,F,FAO estimate,NaN,0.0,Asia,South-Eastern Asia,15207,274.729543,0.000000e+00
1848,38328,TA,Live animals,200,Singapore,5909,Export Quantity,1057,Chickens,2016,...,0.0,F,FAO estimate,NaN,0.0,Asia,South-Eastern Asia,13665,243.356900,0.000000e+00

In [10]:
pivot = recent_traffic.pivot_table(index=['Region','Country'], columns='Year', values='CCM')
pivot.to_excel('report_pollo_traffico_manigoldi.xlsx')

In [12]:
agents = recent_traffic.groupby('Region')
for name, group in agents:
    try:
        os.makedir(name)
    except, e:
        print(f'Folder {name} already exits. Overwriting files')
        print(str(e))

AttributeError: module 'os' has no attribute 'makedir'